name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: docker://vapor/swift:5.0
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Tests
      run: swift test
